<?php 
class TestClass{
	public function __test()
	{
		
	}
	
	private function test()
	{
		
	}
	
	public function _test()
	{
		
	}
	
	public function test_camel_case()
	{
		
	}
	
	function retest_camel_case()
	{
		
	}
}

function __test()
{
	
}

function _package_test()
{
	
}

function package__test()
{
	
}

function Package_()
{
	
}

function Package_test_function()
{
	
}
?>