<?php 
function test ($x= true){
}
function test2 ($x =true){
}
function test3 ($x = true , $y){
}
function test4 ($x = true, Array  $y){
}
function test5 ($x = true,Array $y){
}
function test6 ($x = true,  Array $y){
}
function test7 ($x = true,  $y){
}
function test8 ($x = true,$y){
}
function test9 (Array  $y){
}
function test10 (  Array $y){
}
function test11 (  $y){
}
function test12 (  ){
}
function test13 ($y  ){
}
?>