<?php 


/**
 *
 */
class Test
{
	
}

/**
 * @author Sébastien Roux
 */
class Test2
{
	
}

/**
 * 
 * Begin Short description
 * end short desc
 * 
 * long description
 * @category  Zend
 * @package   TestPackage
 * @copyright Copyright (c) 2005-2010 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd     New BSD License
 */
class Test3
{
	
}

/**
 * begin Short description
 * end short desc
 * 
 * @sometag   Blabla
 * @category  Zend
 * @package   TestPackage
 * @copyright Copyright (c) 2005-2010 Zend Technologies USA Inc. (http://www.zend.com)
 * @license   http://framework.zend.com/license/new-bsd     New BSD License
 */
class Test4
{
	
}

/**
 * Short description
 *
 * @category  Zend
 * @package   
 * @copyright Copyright (c) 2005-2010 Zend Technologies USA Inc. (http://www.zend.com) 
 */
class Test5
{
	
}

/**
 * Short description
 *
 * @category    WrongCategory
 * @package    testPackage
 * @subpackage
 * @copyright  Copyright (c) 2005-2010 Zend Technologies USA Inc. (http://www.zend.com)
 * @see
 * @since        
 * @license    http://framework.zend.com/license/new-bsd     New BSD License
 * @license    http://framework.zend.com/license/new-bsd     New BSD License 
 * @see        Blabla
 * @deprecated 
 */
class Test6
{
	
}

/**
 * Short description
 *
 * @category   Zend
 * @package    TestPackage
 * @subpackage testPackage
 * @see        Blabla
 * @since      bla.1.1
 * @copyright  Copyright (c) 2
 * @copyright  Copyright 
 * @license    http:
 * @deprecated qsdf1.1
 */
class Test7
{
	
}

?>